name: nginx-proxy-manager
services:
  nginx:
    container_name: nginx
    image: jc21/nginx-proxy-manager:latest
    ports:
      - 80:80 # Public HTTP Port
      - 443:443 # Public HTTPS Port
      - 81:81 # Admin Web Port
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
      # Uncomment this if IPv6 is not enabled on your host
      DISABLE_IPV6: 'true'
    volumes:
      - ${BASE_PATH}/ngnix/data:/data
      - ${BASE_PATH}/ngnix/letsencrypt:/etc/letsencrypt
    depends_on:
      db:
        condition: service_started
    restart: unless-stopped

  db:
    container_name: ngnix_db
    image: jc21/mariadb-aria:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
      MARIADB_AUTO_UPGRADE: '1'
    volumes:
      - ${BASE_PATH}/ngnix_db/mysql:/var/lib/mysql
    restart: unless-stopped
