services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: 'bridge'
    ports:
      - 32400:32400
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/Dublin
      - VERSION=docker
    volumes:
      - D:/Docker/plex/config:/config
      - E:/Media:/media:ro
    restart: unless-stopped
    