name: jellyfin
services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    user: 1000:1000
    network_mode: bridge
    ports:
      - 8096:8096
    volumes:
      - ${BASE_PATH}/jellyfin/config:/config
      - ${BASE_PATH}/jellyfin/cache:/cache
      - ${MEDIA_PATH}:/media:ro
    restart: unless-stopped
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
