services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - D:/Docker/homarr/configs:/app/data/configs
      - D:/Docker/homarr/icons:/app/public/icons
      - D:/Docker/homarr/data:/data
    ports:
      - '7575:7575'