name: watchtower-run-once
services:
    watchtower:
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        image: containrrr/watchtower
        environment:
            - WATCHTOWER_CLEANUP=true
        command: --run-once 
        