services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
      - WEBUI_PORT=7044
      - TORRENTING_PORT=6881
    volumes:
      - D:/Docker/qbittorrent/config:/config
      - E:/Downloads:/downloads
    ports:
      - 7044:7044
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    