name: qbittorrent
services:
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Dublin}
      - WEBUI_PORT=7044
      - TORRENTING_PORT=6881
    volumes:
      - ${BASE_PATH}/qbittorrent/config:/config
      - ${DOWNLOADS_PATH}:/downloads
    ports:
      - 7044:7044
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    