name: arr-stack
services:
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Dublin}
      - WEBUI_PORT=7044
      - TORRENTING_PORT=6881
    volumes:
      - ${BASE_PATH}/qbittorrent/config:/config
      - ${DOWNLOADS_PATH}:/downloads
    networks:
      - starr-network
    ports:
      - 7044:7044
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  flaresolverr:
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=${TZ:-Europe/Dublin}
    networks:
      - starr-network
    ports:
      - 8191:8191
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Dublin}
    volumes:
      - ${BASE_PATH}/prowlarr/config:/config
    depends_on:
      flaresolverr:
        condition: service_started
      qbittorrent:
        condition: service_started
    networks:
      - starr-network
    ports:
      - 9696:9696
    restart: unless-stopped

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Dublin}
    volumes:
      - ${BASE_PATH}/sonarr/config:/config
      - ${DOWNLOADS_PATH}:/downloads
      - ${TV_PATH}:/tv
    depends_on:
      prowlarr:
        condition: service_started
    networks:
      - starr-network
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Dublin}
    volumes:
      - ${BASE_PATH}/radarr/config:/config
      - ${MOVIES_PATH}:/movies
      - ${DOWNLOADS_PATH}:/downloads
    depends_on:
      prowlarr:
        condition: service_started
    networks:
      - starr-network
    ports:
      - 7878:7878
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ:-Europe/Dublin}
    volumes:
      - ${BASE_PATH}/jellyseerr:/app/config
    depends_on:
      radarr:
        condition: service_started
      sonarr:
        condition: service_started
    networks:
      - starr-network
    ports:
      - 5055:5055
    restart: unless-stopped

networks:
  starr-network:
    driver: bridge
