services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
      - WEBUI_PORT=7044
      - TORRENTING_PORT=6881
    volumes:
      - D:/Docker/qbittorrent/config:/config
      - E:/Downloads:/downloads
    networks:
      - starr-network
    ports:
      - 7044:7044
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=Europe/Dublin
    networks:
      - starr-network
    ports:
      - 8191:8191
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
    volumes:
      - D:/Docker/prowlarr/config:/config
    depends_on:
      flaresolverr:
        condition: service_started
      qbittorrent:
        condition: service_started
    networks:
      - starr-network
    ports:
      - 9696:9696
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
    volumes:
      - D:/Docker/sonarr/config:/config
      - "E:/Media/TV Shows:/tv"
      - E:/Downloads:/downloads
    depends_on:
      prowlarr:
        condition: service_started
    networks:
      - starr-network
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
    volumes:
      - D:/Docker/radarr/config:/config
      - E:/Media/Movies:/movies
      - E:/Downloads:/downloads
    depends_on:
      prowlarr:
        condition: service_started
    networks:
      - starr-network
    ports:
      - 7878:7878
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Dublin
    volumes:
      - D:/Docker/jellyseerr:/app/config
    depends_on:
      radarr:
        condition: service_started
      sonarr:
        condition: service_started
    networks:
      - starr-network
    ports:
      - 5055:5055
    restart: unless-stopped

networks:
  starr-network:
    driver: bridge
