services:
  app:
    image: fireflyiii/core:latest
    hostname: app
    container_name: firefly_iii_core
    restart: always
    volumes:
      - ${BASE_PATH}/firefly_iii/upload:/var/www/html/storage/upload
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - SITE_OWNER=${SITE_OWNER}
      - APP_KEY=${APP_KEY}
      - DEFAULT_LANGUAGE=en_US
      - DEFAULT_LOCALE=equal
      - TZ=Europe/Dublin
      - TRUSTED_PROXIES=${TRUSTED_PROXIES}
      - LOG_CHANNEL=stack
      - APP_LOG_LEVEL=notice
      - AUDIT_LOG_LEVEL=emergency
      - AUDIT_LOG_CHANNEL=
      - PAPERTRAIL_HOST=
      - PAPERTRAIL_PORT=
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_SOCKET=
      - MYSQL_USE_SSL=false
      - MYSQL_SSL_VERIFY_SERVER_CERT=true
      - MYSQL_SSL_CAPATH=/etc/ssl/certs/
      - MYSQL_SSL_CA=
      - MYSQL_SSL_CERT=
      - MYSQL_SSL_KEY=
      - MYSQL_SSL_CIPHER=
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - COOKIE_PATH="/"
      - COOKIE_DOMAIN=
      - COOKIE_SECURE=false
      - COOKIE_SAMESITE=lax
      - MAIL_MAILER=log
      - MAIL_HOST=null
      - MAIL_PORT=2525
      - MAIL_FROM=changeme@example.com
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null
      - MAIL_SENDMAIL_COMMAND=
      - MAIL_ALLOW_SELF_SIGNED=false
      - MAIL_VERIFY_PEER=true
      - MAIL_VERIFY_PEER_NAME=true
      - MAILGUN_DOMAIN=
      - MAILGUN_SECRET=
      - MAILGUN_ENDPOINT=api.mailgun.net
      - MANDRILL_SECRET=
      - SPARKPOST_SECRET=
      - MAILERSEND_API_KEY=
      - SEND_ERROR_MESSAGE=true
      - SEND_REPORT_JOURNALS=true
      - ENABLE_EXTERNAL_MAP=false
      - ENABLE_EXCHANGE_RATES=false
      - ENABLE_EXTERNAL_RATES=false
      - MAP_DEFAULT_LAT=51.983333
      - MAP_DEFAULT_LONG=5.916667
      - MAP_DEFAULT_ZOOM=6
      - VALID_URL_PROTOCOLS=
      - AUTHENTICATION_GUARD=web
      - AUTHENTICATION_GUARD_HEADER=REMOTE_USER
      - AUTHENTICATION_GUARD_EMAIL=
      - PASSPORT_PRIVATE_KEY=
      - PASSPORT_PUBLIC_KEY=
      - CUSTOM_LOGOUT_URL=
      - DISABLE_FRAME_HEADER=false
      - DISABLE_CSP_HEADER=false
      - TRACKER_SITE_ID=
      - TRACKER_URL=
      - ALLOW_WEBHOOKS=false
      - STATIC_CRON_TOKEN=
      - DKR_BUILD_LOCALE=false
      - DKR_CHECK_SQLITE=true
      - APP_NAME=FireflyIII
      - BROADCAST_DRIVER=log
      - QUEUE_DRIVER=sync
      - CACHE_PREFIX=firefly
      - PUSHER_KEY=
      - IPINFO_TOKEN=
      - PUSHER_SECRET=
      - PUSHER_ID=
      - DEMO_USERNAME=
      - DEMO_PASSWORD=
      - USE_RUNNING_BALANCE=false
      - FIREFLY_III_LAYOUT=v1
      - QUERY_PARSER_IMPLEMENTATION=legacy
      - APP_URL=http://localhost

    networks:
      - firefly_iii
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: mysql
    hostname: db
    container_name: firefly_iii_db
    restart: always
    networks:
      - firefly_iii
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=${MYSQL_RANDOM_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ${BASE_PATH}/firefly_iii/db:/var/lib/mysql
  cron:
    #
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable and replace PLEASE_REPLACE_WITH_32_CHAR_CODE below
    # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
    #
    image: alpine
    restart: always
    container_name: firefly_iii_cron
    command: sh -c "
      apk add tzdata
      && ln -s /usr/share/zoneinfo/${TZ} /etc/localtime
      | echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/aWmydSvK0RhiuJ6R1dG2IaC8YLvLUOpJ;echo\" 
      | crontab - 
      && crond -f -L /dev/stdout"
    networks:
      - firefly_iii

networks:
  firefly_iii:
    driver: bridge
