name: emulatorjs
services:
  emulatorjs:
    container_name: emulatorjs
    image: lscr.io/linuxserver/emulatorjs:latest
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Dublin}
      - SUBFOLDER=/
    volumes:
      - ${BASE_PATH}/emulatorjs/config:/config
      - ${GAMES_PATH}/ROMs/gba:/data/gba
    ports:
      - 3081:3000
      - 3080:80
      - 4001:4001
    restart: unless-stopped