services:
  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    user: 0:0
    environment:
      - TZ=${TZ:-Europe/Dublin}
      - PASSWORD=${PASSWORD}
    ports:
      - 8080:8080
    volumes:
      # --- VS Code Settings & Extensions ---
      - ${BASE_PATH}/vscode/config:/root/.config/code-server
      - ${BASE_PATH}/vscode/extensions:/root/.local/share/code-server
      # --- Mounts For Git Persistence ---
      - ${BASE_PATH}/vscode/ssh:/root/.ssh
      - ${BASE_PATH}/vscode/.gitconfig:/root/.gitconfig
      # --- Projects ---  
      - ${BASE_PATH}/vscode/projects:/home/coder/project
    restart: unless-stopped
