services:
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    network_mode: bridge
    ports:
      - 32400:32400
    environment:
      - PUID=${PUID:-1000}
      - GUID=${PGID:-1000}
      - TZ=${TZ:-Europe/Dublin}
      - VERSION=docker
    volumes:
      - ${BASE_PATH}/plex/config:/config
      - ${MEDIA_PATH}:/media:ro
    restart: unless-stopped
    