services:
  opencloud:
    image: opencloudeu/opencloud-rolling
    container_name: opencloud
    user: "0:0"
    volumes:
      - ${BASE_PATH}/opencloud/data:/var/lib/opencloud
      - ${BASE_PATH}/opencloud/config:/etc/opencloud
      - ${STORAGE_PATH}/opencloud/users:/var/lib/opencloud/storage/users
    ports:
      - "9200:9200"
    entrypoint:
      - /bin/sh
    command: ["-c", "opencloud init || true; opencloud server"]
    environment:
      - OC_URL=https://drive.mydomain.com
      - IDM_CREATE_DEMO_USERS=false
      - OC_INSECURE=true
      - PROXY_TLS=false
      - "JWT_SECRET=${JWT_SECRET}"
      - NATS_NATS_HOST=0.0.0.0
      - GATEWAY_GRPC_ADDR=0.0.0.0:9142
      - FRONTEND_APP_HANDLER_SECURE_VIEW_APP_ADDR=http://collaboration:9300
      - PROXY_CSP_CONFIG_FILE_LOCATION=/etc/opencloud/csp.yaml
    restart: unless-stopped

  collaboration:
    image: opencloudeu/opencloud-rolling
    container_name: collaboration
    user: "0:0"
    volumes:
      - ${BASE_PATH}/opencloud/config:/etc/opencloud
    depends_on:
      - opencloud
      - collabora
    entrypoint:
      - /bin/sh
    command: ["-c", "while [ ! -f /etc/opencloud/opencloud.yaml ]; do echo 'Waiting for config...'; sleep 2; done; sleep 10; echo 'Starting collaboration server'; exec opencloud collaboration server"]
    environment:
      - "JWT_SECRET=${JWT_SECRET}"
      - COLLABORATION_GRPC_ADDR=0.0.0.0:9301
      - COLLABORATION_HTTP_ADDR=0.0.0.0:9300
      - MICRO_REGISTRY=nats-js-kv
      - MICRO_REGISTRY_ADDRESS=opencloud:9233
      - COLLABORATION_WOPI_SRC=https://drive.mydomain.com
      - COLLABORATION_APP_NAME=CollaboraOnline
      - COLLABORATION_APP_PRODUCT=Collabora
      - COLLABORATION_APP_ADDR=https://office.mydomain.com
      - COLLABORATION_APP_INTERNAL_URL=http://collabora:9980
      - COLLABORATION_APP_INSECURE=true
      - COLLABORATION_APP_PROOF_DISABLE=true
      - COLLABORATION_CS3API_DATAGATEWAY_INSECURE=true
      - OC_URL=https://drive.mydomain.com
    restart: unless-stopped

  collabora:
    image: collabora/code:latest
    container_name: collabora
    environment:
      - "aliasgroup1=https://drive.mydomain.com:443"
      - "extra_params=--o:ssl.enable=false --o:ssl.termination=true --o:net.frame_ancestors=https://drive.mydomain.com"
      - DONT_GEN_SSL_CERT=1
      - "dictionaries=en_GB en_US"
    ports:
      - "9980:9980"
    restart: unless-stopped
