name: homeassistant
services:
    homeassistant:
        container_name: homeassistant
        image: ghcr.io/home-assistant/home-assistant:stable
        privileged: true
        network_mode: bridge
        ports:
            - 8123:8123
        environment:
            - TZ=${TZ:-Europe/Dublin}
        volumes:
            - ${BASE_PATH}/homeassistant/config:/config
            - /run/dbus:/run/dbus:ro
        restart: unless-stopped
            