name: uptime-kuma
services:
    uptime-kuma:
        container_name: uptime-kuma
        image: louislam/uptime-kuma:1
        ports:
            - 3001:3001
        volumes:
            - ${BASE_PATH}/uptime-kuma:/app/data
        restart: unless-stopped
